# -*- coding: utf-8 -*-
"""CS335_PythonLab1_AlexVazquez.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tKhz9JTf8x7VDcRvvVBsGns-vtPWP0Y1
"""

name = "Alex Vazquez"
age = 23
ai_course = True
print("Name:", name)
print("Age in 5 years:", age + 5)
print("Is enrolled in CS 335 course?", ai_course)

topics = ["Logic", "Search", "NLP", "ML", "Bayesian Inference", "Semantic Search", "RAG"]
for topic in topics:
  i = topics.index(topic) + 1
  print("We will study: ", str(i) + ".", topic)

student = {"name": "Omeed", "score": 94}
if student["score"] >= 95:
 grade = "A+"
elif student["score"] in range(90, 95):
 grade = "A"
elif student["score"] >= 80:
 grade = "B"
else:
 grade = "C or below"
print(f"{student['name']} received a grade of {grade}.")

def greet_student(name):
  return f"Welcome to Omeed, {name}!"
# Test
print(greet_student("Omeed"))

def square_number(number):
  return number * number

print(square_number(12))